services:
  postgres:
    image: postgres:14
    platform: linux/amd64
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: patients
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
        - ./customer-service/migrations:/docker-entrypoint-initdb.d

  customer-service:
    build: ./customer-service
    platform: linux/amd64
    ports:
      - "8081:8081"
    depends_on:
      - postgres

  # ... остальные сервисы

volumes:
  pgdata: